jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup redis 1
      uses: getong/redis-action@v1
      with:
        container port: 6380
        host port: 6380
        redis password: test
        redis version: 3.2.3
    - continue-on-error: true
      name: Setup redis 2
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: 6.x
    - continue-on-error: true
      name: Setup JDK 11 for compile
      uses: actions/setup-java@v3
      with:
        check-latest: false
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Compile
      run: mvn clean package -DskipTests -P CI --batch-mode --quiet
    - continue-on-error: true
      name: Setup JDK ${{ matrix.java }} for running
      uses: actions/setup-java@v3
      with:
        check-latest: false
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Version
      run: java -version
    - continue-on-error: true
      name: Test
      run: mvn test jacoco:report coveralls:report --batch-mode --quiet
    strategy:
      matrix:
        java:
        - '8'
        - '11'
        - '17'
        - '21'
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
