jobs:
  release:
    name: Release on Sonatype OSS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        check-latest: false
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: '11'
        server-id: ossrh
        server-password: OSSRH_PASSWORD
        server-username: OSSRH_USERNAME
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish to Apache Maven Central
      run: mvn clean deploy -Prelease -DskipTests
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
